#!/usr/bin/env bash
set -e

IMAGE="progrium/buildstep"

CMD="(mkdir /tmp/mon && cd /tmp/mon && curl -L# https://github.com/visionmedia/mon/archive/master.tar.gz | tar zx --strip 1 && make install && rm -rf /tmp/mon)"

ID=$(docker run -d $IMAGE /bin/sh -c "$CMD")
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $IMAGE > /dev/null
